name:                giama-backend
version:             0.1.0.0
github:              "githubuser/giama-backend"
license:             BSD3
author:              "Enrico Benini"
maintainer:          "benkio89@gmail.com"
copyright:           "2020 Enrico Benini"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/benkio/giama-backend#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- servant-server
- wai
- warp
- directory
- filepath
- either
#- transformers

library:
  source-dirs: src

executables:
  giama-backend-Api-exe:
    main:                ApiMain.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is ApiMain
    dependencies:
    - base
    - giama-backend
  giama-backend-Shell-exe:
    main:                ShellMain.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is ShellMain
    dependencies:
    - base
    - giama-backend

    
tests:
  giama-backend-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - giama-backend
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
